"""Add tokens_used column

Revision ID: 6a930b395d31
Revises: 3bf288134dfc
Create Date: 2026-04-30 12:33:50.089446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a930b395d31'
down_revision: Union[str, None] = '3bf288134dfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('tokens_used', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'tokens_used')
    # ### end Alembic commands ###
